---
name: Build and test

"on":
  push:
    branches: [main, rewrite]
    paths-ignore:
      - "Docs/**"
      - "**.md"
      - "README.md"
      - "LICENSE"
      - ".gitignore"
  pull_request:
    branches: ["**"]
    paths-ignore:
      - "Docs/**"
      - "**.md"
      - "README.md"
      - "LICENSE"
      - ".gitignore"

jobs:
  build-devcontainer:
    name: "Devcontainer: ${{ matrix.host.os }}/${{ matrix.configuration }}"
    strategy:
      fail-fast: false
      matrix:
        options: [
          {
            build: "-v --build-tests -Xswiftc -enable-testing",
            test: "-v"
          }
        ]
        os: [ubuntu-latest]
        configuration: [debug, release]

    runs-on: ${{ matrix.host.os }}
    steps:
      - uses: actions/checkout@v3

      - run: git config --global core.autocrlf input

      - name: Build and Test
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            swift build -c ${{ matrix.configuration }} \
              ${{ matrix.options.build }} &&

            swift test -c ${{ matrix.configuration }} ${{  options.test }}

  build-native:
    name: "Native: ${{ matrix.host.os }}/${{ matrix.configuration }}"
    strategy:
      fail-fast: false
      matrix:
        options: [
          {
            build: "-v --build-tests -Xswiftc -enable-testing",
            test: "-v"
          }
        ]
        os: [macos-latest, ubuntu-latest, windows-latest]
        swift: [{version: "5.8"}]
        configuration: [debug, release]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: git config --global core.autocrlf input

      - name: Setup swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift.version }}

      - run: swift --version

      - name: Build (${{ matrix.configuration }})
        run: |
          export PKG_CONFIG_PATH=$PWD &&

          swift build -c ${{ matrix.configuration }} ${{ matrix.options.build }}

      - name: Test (${{ matrix.configuration }})
        run: |
          export PKG_CONFIG_PATH=$PWD &&

          swift test -c ${{ matrix.configuration }} ${{ matrix.options.test }}
